// Hand-written, concrete request-param/body types matching the generated Zod
// schemas in ./generated/api.
//
// Why explicit interfaces (not `z.infer<typeof Schema>`): route handlers in
// @workspace/api-server read `.safeParse(...).data`. The generated schema
// output type is a deep Zod conditional type that does NOT materialize across
// the package boundary unless `zod` is loaded in the consuming module's type
// space, so the inferred shape silently collapses to `{}`. A `z.infer<...>`
// re-export does not help because TypeScript preserves the alias in the emitted
// .d.ts. Declaring the shapes explicitly here decouples consumers from Zod's
// inference entirely and yields stable, self-contained types.
//
// This file is NOT generated by orval and is safe from codegen overwrites.
// Keep in sync with ./generated/api if the OpenAPI spec changes.

import type { ShipmentStatus } from "./generated/types/shipmentStatus";

export interface ListShipmentsQuery {
  status?: ShipmentStatus;
  customerId?: number | null;
  search?: string;
  page: number;
  limit: number;
}

export interface ListCustomersQuery {
  search?: string;
  page: number;
}

export interface IdParam {
  id: number;
}

export interface AddTrackingEventInput {
  status: string;
  location: string;
  description: string;
  timestamp?: string;
}

export interface TrackingNumberParam {
  trackingNumber: string;
}
